const countriesList = [
  {code: "af", name: "Afghanistan", nationality: "Afghan", nativeName: "افغانستان"},
  {code: "ax", name: "Åland Islands", nationality: "Ålandish", nativeName: "Åland"},
  {code: "al", name: "Albania", nationality: "Albanian", nativeName: "Shqipëria"},
  {code: "dz", name: "Algeria", nationality: "Algerian", nativeName: "الجزائر"},
  {code: "as", name: "American Samoa", nationality: "American Samoan", nativeName: "American Samoa"},
  {code: "ad", name: "Andorra", nationality: "Andorran", nativeName: "Andorra"},
  {code: "ao", name: "Angola", nationality: "Angolan", nativeName: "Angola"},
  {code: "ai", name: "Anguilla", nationality: "Anguillian", nativeName: "Anguilla"},
  {code: "aq", name: "Antarctica", nationality: "", nativeName: "Antarctica"},
  {code: "ag", name: "Antigua and Barbuda", nationality: "Antiguan, Barbudan", nativeName: "Antigua and Barbuda"},
  {code: "ar", name: "Argentina", nationality: "Argentinean", nativeName: "Argentina"},
  {code: "am", name: "Armenia", nationality: "Armenian", nativeName: "Հայաստան"},
  {code: "aw", name: "Aruba", nationality: "Aruban", nativeName: "Aruba"},
  {code: "au", name: "Australia", nationality: "Australian", nativeName: "Australia"},
  {code: "at", name: "Austria", nationality: "Austrian", nativeName: "Österreich"},
  {code: "az", name: "Azerbaijan", nationality: "Azerbaijani", nativeName: "Azərbaycan"},
  {code: "bs", name: "Bahamas", nationality: "Bahamian", nativeName: "Bahamas"},
  {code: "bh", name: "Bahrain", nationality: "Bahraini", nativeName: "‏البحرين"},
  {code: "bd", name: "Bangladesh", nationality: "Bangladeshi", nativeName: "Bangladesh"},
  {code: "bb", name: "Barbados", nationality: "Barbadian", nativeName: "Barbados"},
  {code: "by", name: "Belarus", nationality: "Belarusian", nativeName: "Белару́сь"},
  {code: "be", name: "Belgium", nationality: "Belgian", nativeName: "België"},
  {code: "bz", name: "Belize", nationality: "Belizean", nativeName: "Belize"},
  {code: "bj", name: "Benin", nationality: "Beninese", nativeName: "Bénin"},
  {code: "bm", name: "Bermuda", nationality: "Bermudian", nativeName: "Bermuda"},
  {code: "bt", name: "Bhutan", nationality: "Bhutanese", nativeName: "ʼbrug-yul"},
  {code: "bo", name: "Bolivia (Plurinational State of)", nationality: "Bolivian", nativeName: "Bolivia"},
  {code: "bq", name: "Bonaire, Sint Eustatius and Saba", nationality: "Dutch", nativeName: "Bonaire"},
  {code: "ba", name: "Bosnia and Herzegovina", nationality: "Bosnian, Herzegovinian", nativeName: "Bosna i Hercegovina"},
  {code: "bw", name: "Botswana", nationality: "Motswana", nativeName: "Botswana"},
  {code: "bv", name: "Bouvet Island", nationality: "", nativeName: "Bouvetøya"},
  {code: "br", name: "Brazil", nationality: "Brazilian", nativeName: "Brasil"},
  {code: "io", name: "British Indian Ocean Territory", nationality: "Indian", nativeName: "British Indian Ocean Territory"},
  {code: "bn", name: "Brunei Darussalam", nationality: "Bruneian", nativeName: "Negara Brunei Darussalam"},
  {code: "bg", name: "Bulgaria", nationality: "Bulgarian", nativeName: "България"},
  {code: "bf", name: "Burkina Faso", nationality: "Burkinabe", nativeName: "Burkina Faso"},
  {code: "bi", name: "Burundi", nationality: "Burundian", nativeName: "Burundi"},
  {code: "cv", name: "Cabo Verde", nationality: "Cape Verdian", nativeName: "Cabo Verde"},
  {code: "kh", name: "Cambodia", nationality: "Cambodian", nativeName: "Kâmpŭchéa"},
  {code: "cm", name: "Cameroon", nationality: "Cameroonian", nativeName: "Cameroon"},
  {code: "ca", name: "Canada", nationality: "Canadian", nativeName: "Canada"},
  {code: "ky", name: "Cayman Islands", nationality: "Caymanian", nativeName: "Cayman Islands"},
  {code: "cf", name: "Central African Republic", nationality: "Central African", nativeName: "Ködörösêse tî Bêafrîka"},
  {code: "td", name: "Chad", nationality: "Chadian", nativeName: "Tchad"},
  {code: "cl", name: "Chile", nationality: "Chilean", nativeName: "Chile"},
  {code: "cn", name: "China", nationality: "Chinese", nativeName: "中国"},
  {code: "cx", name: "Christmas Island", nationality: "Christmas Island", nativeName: "Christmas Island"},
  {code: "cc", name: "Cocos (Keeling) Islands", nationality: "Cocos Islander", nativeName: "Cocos (Keeling) Islands"},
  {code: "co", name: "Colombia", nationality: "Colombian", nativeName: "Colombia"},
  {code: "km", name: "Comoros", nationality: "Comoran", nativeName: "Komori"},
  {code: "cg", name: "Congo", nationality: "Congolese", nativeName: "République du Congo"},
  {code: "cd", name: "Congo (Democratic Republic of the)", nationality: "Congolese", nativeName: "République démocratique du Congo"},
  {code: "ck", name: "Cook Islands", nationality: "Cook Islander", nativeName: "Cook Islands"},
  {code: "cr", name: "Costa Rica", nationality: "Costa Rican", nativeName: "Costa Rica"},
  {code: "ci", name: "Côte d'Ivoire", nationality: "Ivorian", nativeName: "Côte d'Ivoire"},
  {code: "hr", name: "Croatia", nationality: "Croatian", nativeName: "Hrvatska"},
  {code: "cu", name: "Cuba", nationality: "Cuban", nativeName: "Cuba"},
  {code: "cw", name: "Curaçao", nationality: "Dutch", nativeName: "Curaçao"},
  {code: "cy", name: "Cyprus", nationality: "Cypriot", nativeName: "Κύπρος"},
  {code: "cz", name: "Czech Republic", nationality: "Czech", nativeName: "Česká republika"},
  {code: "dk", name: "Denmark", nationality: "Danish", nativeName: "Danmark"},
  {code: "dj", name: "Djibouti", nationality: "Djibouti", nativeName: "Djibouti"},
  {code: "dm", name: "Dominica", nationality: "Dominican", nativeName: "Dominica"},
  {code: "do", name: "Dominican Republic", nationality: "Dominican", nativeName: "República Dominicana"},
  {code: "ec", name: "Ecuador", nationality: "Ecuadorean", nativeName: "Ecuador"},
  {code: "eg", name: "Egypt", nationality: "Egyptian", nativeName: "مصر‎"},
  {code: "sv", name: "El Salvador", nationality: "Salvadoran", nativeName: "El Salvador"},
  {code: "gq", name: "Equatorial Guinea", nationality: "Equatorial Guinean", nativeName: "Guinea Ecuatorial"},
  {code: "er", name: "Eritrea", nationality: "Eritrean", nativeName: "ኤርትራ"},
  {code: "ee", name: "Estonia", nationality: "Estonian", nativeName: "Eesti"},
  {code: "et", name: "Ethiopia", nationality: "Ethiopian", nativeName: "ኢትዮጵያ"},
  {code: "fk", name: "Falkland Islands (Malvinas)", nationality: "Falkland Islander", nativeName: "Falkland Islands"},
  {code: "fo", name: "Faroe Islands", nationality: "Faroese", nativeName: "Føroyar"},
  {code: "fj", name: "Fiji", nationality: "Fijian", nativeName: "Fiji"},
  {code: "fi", name: "Finland", nationality: "Finnish", nativeName: "Suomi"},
  {code: "fr", name: "France", nationality: "French", nativeName: "France"},
  {code: "gf", name: "French Guiana", nationality: "", nativeName: "Guyane française"},
  {code: "pf", name: "French Polynesia", nationality: "French Polynesian", nativeName: "Polynésie française"},
  {code: "tf", name: "French Southern Territories", nationality: "French", nativeName: "Territoire des Terres australes et antarctiques françaises"},
  {code: "ga", name: "Gabon", nationality: "Gabonese", nativeName: "Gabon"},
  {code: "gm", name: "Gambia", nationality: "Gambian", nativeName: "Gambia"},
  {code: "ge", name: "Georgia", nationality: "Georgian", nativeName: "საქართველო"},
  {code: "de", name: "Germany", nationality: "German", nativeName: "Deutschland"},
  {code: "gh", name: "Ghana", nationality: "Ghanaian", nativeName: "Ghana"},
  {code: "gi", name: "Gibraltar", nationality: "Gibraltar", nativeName: "Gibraltar"},
  {code: "gr", name: "Greece", nationality: "Greek", nativeName: "Ελλάδα"},
  {code: "gl", name: "Greenland", nationality: "Greenlandic", nativeName: "Kalaallit Nunaat"},
  {code: "gd", name: "Grenada", nationality: "Grenadian", nativeName: "Grenada"},
  {code: "gp", name: "Guadeloupe", nationality: "Guadeloupian", nativeName: "Guadeloupe"},
  {code: "gu", name: "Guam", nationality: "Guamanian", nativeName: "Guam"},
  {code: "gt", name: "Guatemala", nationality: "Guatemalan", nativeName: "Guatemala"},
  {code: "gg", name: "Guernsey", nationality: "Channel Islander", nativeName: "Guernsey"},
  {code: "gn", name: "Guinea", nationality: "Guinean", nativeName: "Guinée"},
  {code: "gw", name: "Guinea-Bissau", nationality: "Guinea-Bissauan", nativeName: "Guiné-Bissau"},
  {code: "gy", name: "Guyana", nationality: "Guyanese", nativeName: "Guyana"},
  {code: "ht", name: "Haiti", nationality: "Haitian", nativeName: "Haïti"},
  {code: "hm", name: "Heard Island and McDonald Islands", nationality: "Heard and McDonald Islander", nativeName: "Heard Island and McDonald Islands"},
  {code: "va", name: "Holy See", nationality: "", nativeName: "Sancta Sedes"},
  {code: "hn", name: "Honduras", nationality: "Honduran", nativeName: "Honduras"},
  {code: "hk", name: "Hong Kong", nationality: "Chinese", nativeName: "香港"},
  {code: "hu", name: "Hungary", nationality: "Hungarian", nativeName: "Magyarország"},
  {code: "is", name: "Iceland", nationality: "Icelander", nativeName: "Ísland"},
  {code: "in", name: "India", nationality: "Indian", nativeName: "भारत"},
  {code: "id", name: "Indonesia", nationality: "Indonesian", nativeName: "Indonesia"},
  {code: "ir", name: "Iran (Islamic Republic of)", nationality: "Iranian", nativeName: "ایران"},
  {code: "iq", name: "Iraq", nationality: "Iraqi", nativeName: "العراق"},
  {code: "ie", name: "Ireland", nationality: "Irish", nativeName: "Éire"},
  {code: "im", name: "Isle of Man", nationality: "Manx", nativeName: "Isle of Man"},
  {code: "il", name: "Israel", nationality: "Israeli", nativeName: "יִשְׂרָאֵל"},
  {code: "it", name: "Italy", nationality: "Italian", nativeName: "Italia"},
  {code: "jm", name: "Jamaica", nationality: "Jamaican", nativeName: "Jamaica"},
  {code: "jp", name: "Japan", nationality: "Japanese", nativeName: "日本"},
  {code: "je", name: "Jersey", nationality: "Channel Islander", nativeName: "Jersey"},
  {code: "jo", name: "Jordan", nationality: "Jordanian", nativeName: "الأردن"},
  {code: "kz", name: "Kazakhstan", nationality: "Kazakhstani", nativeName: "Қазақстан"},
  {code: "ke", name: "Kenya", nationality: "Kenyan", nativeName: "Kenya"},
  {code: "ki", name: "Kiribati", nationality: "I-Kiribati", nativeName: "Kiribati"},
  {code: "kp", name: "Korea (Democratic People's Republic of)", nationality: "North Korean", nativeName: "북한"},
  {code: "kr", name: "Korea (Republic of)", nationality: "South Korean", nativeName: "대한민국"},
  {code: "kw", name: "Kuwait", nationality: "Kuwaiti", nativeName: "الكويت"},
  {code: "kg", name: "Kyrgyzstan", nationality: "Kirghiz", nativeName: "Кыргызстан"},
  {code: "la", name: "Lao People's Democratic Republic", nationality: "Laotian", nativeName: "ສປປລາວ"},
  {code: "lv", name: "Latvia", nationality: "Latvian", nativeName: "Latvija"},
  {code: "lb", name: "Lebanon", nationality: "Lebanese", nativeName: "لبنان"},
  {code: "ls", name: "Lesotho", nationality: "Mosotho", nativeName: "Lesotho"},
  {code: "lr", name: "Liberia", nationality: "Liberian", nativeName: "Liberia"},
  {code: "ly", name: "Libya", nationality: "Libyan", nativeName: "‏ليبيا"},
  {code: "li", name: "Liechtenstein", nationality: "Liechtensteiner", nativeName: "Liechtenstein"},
  {code: "lt", name: "Lithuania", nationality: "Lithuanian", nativeName: "Lietuva"},
  {code: "lu", name: "Luxembourg", nationality: "Luxembourger", nativeName: "Luxembourg"},
  {code: "mo", name: "Macao", nationality: "Chinese", nativeName: "澳門"},
  {code: "mk", name: "Macedonia (the former Yugoslav Republic of)", nationality: "Macedonian", nativeName: "Македонија"},
  {code: "mg", name: "Madagascar", nationality: "Malagasy", nativeName: "Madagasikara"},
  {code: "mw", name: "Malawi", nationality: "Malawian", nativeName: "Malawi"},
  {code: "my", name: "Malaysia", nationality: "Malaysian", nativeName: "Malaysia"},
  {code: "mv", name: "Maldives", nationality: "Maldivan", nativeName: "Maldives"},
  {code: "ml", name: "Mali", nationality: "Malian", nativeName: "Mali"},
  {code: "mt", name: "Malta", nationality: "Maltese", nativeName: "Malta"},
  {code: "mh", name: "Marshall Islands", nationality: "Marshallese", nativeName: "M̧ajeļ"},
  {code: "mq", name: "Martinique", nationality: "French", nativeName: "Martinique"},
  {code: "mr", name: "Mauritania", nationality: "Mauritanian", nativeName: "موريتانيا"},
  {code: "mu", name: "Mauritius", nationality: "Mauritian", nativeName: "Maurice"},
  {code: "yt", name: "Mayotte", nationality: "French", nativeName: "Mayotte"},
  {code: "mx", name: "Mexico", nationality: "Mexican", nativeName: "México"},
  {code: "fm", name: "Micronesia (Federated States of)", nationality: "Micronesian", nativeName: "Micronesia"},
  {code: "md", name: "Moldova (Republic of)", nationality: "Moldovan", nativeName: "Moldova"},
  {code: "mc", name: "Monaco", nationality: "Monegasque", nativeName: "Monaco"},
  {code: "mn", name: "Mongolia", nationality: "Mongolian", nativeName: "Монгол улс"},
  {code: "me", name: "Montenegro", nationality: "Montenegrin", nativeName: "Црна Гора"},
  {code: "ms", name: "Montserrat", nationality: "Montserratian", nativeName: "Montserrat"},
  {code: "ma", name: "Morocco", nationality: "Moroccan", nativeName: "المغرب"},
  {code: "mz", name: "Mozambique", nationality: "Mozambican", nativeName: "Moçambique"},
  {code: "mm", name: "Myanmar", nationality: "Burmese", nativeName: "Myanma"},
  {code: "na", name: "Namibia", nationality: "Namibian", nativeName: "Namibia"},
  {code: "nr", name: "Nauru", nationality: "Nauruan", nativeName: "Nauru"},
  {code: "np", name: "Nepal", nationality: "Nepalese", nativeName: "नेपाल"},
  {code: "nl", name: "Netherlands", nationality: "Dutch", nativeName: "Nederland"},
  {code: "nc", name: "New Caledonia", nationality: "New Caledonian", nativeName: "Nouvelle-Calédonie"},
  {code: "nz", name: "New Zealand", nationality: "New Zealander", nativeName: "New Zealand"},
  {code: "ni", name: "Nicaragua", nationality: "Nicaraguan", nativeName: "Nicaragua"},
  {code: "ne", name: "Niger", nationality: "Nigerien", nativeName: "Niger"},
  {code: "ng", name: "Nigeria", nationality: "Nigerian", nativeName: "Nigeria"},
  {code: "nu", name: "Niue", nationality: "Niuean", nativeName: "Niuē"},
  {code: "nf", name: "Norfolk Island", nationality: "Norfolk Islander", nativeName: "Norfolk Island"},
  {code: "mp", name: "Northern Mariana Islands", nationality: "American", nativeName: "Northern Mariana Islands"},
  {code: "no", name: "Norway", nationality: "Norwegian", nativeName: "Norge"},
  {code: "om", name: "Oman", nationality: "Omani", nativeName: "عمان"},
  {code: "pk", name: "Pakistan", nationality: "Pakistani", nativeName: "Pakistan"},
  {code: "pw", name: "Palau", nationality: "Palauan", nativeName: "Palau"},
  {code: "ps", name: "Palestine, State of", nationality: "Palestinian", nativeName: "فلسطين"},
  {code: "pa", name: "Panama", nationality: "Panamanian", nativeName: "Panamá"},
  {code: "pg", name: "Papua New Guinea", nationality: "Papua New Guinean", nativeName: "Papua Niugini"},
  {code: "py", name: "Paraguay", nationality: "Paraguayan", nativeName: "Paraguay"},
  {code: "pe", name: "Peru", nationality: "Peruvian", nativeName: "Perú"},
  {code: "ph", name: "Philippines", nationality: "Filipino", nativeName: "Pilipinas"},
  {code: "pn", name: "Pitcairn", nationality: "Pitcairn Islander", nativeName: "Pitcairn Islands"},
  {code: "pl", name: "Poland", nationality: "Polish", nativeName: "Polska"},
  {code: "pt", name: "Portugal", nationality: "Portuguese", nativeName: "Portugal"},
  {code: "pr", name: "Puerto Rico", nationality: "Puerto Rican", nativeName: "Puerto Rico"},
  {code: "qa", name: "Qatar", nationality: "Qatari", nativeName: "قطر"},
  {code: "xk", name: "Republic of Kosovo", nationality: "Kosovar", nativeName: "Republika e Kosovës"},
  {code: "re", name: "Réunion", nationality: "French", nativeName: "La Réunion"},
  {code: "ro", name: "Romania", nationality: "Romanian", nativeName: "România"},
  {code: "ru", name: "Russian Federation", nationality: "Russian", nativeName: "Россия"},
  {code: "rw", name: "Rwanda", nationality: "Rwandan", nativeName: "Rwanda"},
  {code: "bl", name: "Saint Barthélemy", nationality: "Saint Barthélemy Islander", nativeName: "Saint-Barthélemy"},
  {code: "sh", name: "Saint Helena, Ascension and Tristan da Cunha", nationality: "Saint Helenian", nativeName: "Saint Helena"},
  {code: "kn", name: "Saint Kitts and Nevis", nationality: "Kittian and Nevisian", nativeName: "Saint Kitts and Nevis"},
  {code: "lc", name: "Saint Lucia", nationality: "Saint Lucian", nativeName: "Saint Lucia"},
  {code: "mf", name: "Saint Martin (French part)", nationality: "Saint Martin Islander", nativeName: "Saint-Martin"},
  {code: "pm", name: "Saint Pierre and Miquelon", nationality: "French", nativeName: "Saint-Pierre-et-Miquelon"},
  {code: "vc", name: "Saint Vincent and the Grenadines", nationality: "Saint Vincentian", nativeName: "Saint Vincent and the Grenadines"},
  {code: "ws", name: "Samoa", nationality: "Samoan", nativeName: "Samoa"},
  {code: "sm", name: "San Marino", nationality: "Sammarinese", nativeName: "San Marino"},
  {code: "st", name: "Sao Tome and Principe", nationality: "Sao Tomean", nativeName: "São Tomé e Príncipe"},
  {code: "sa", name: "Saudi Arabia", nationality: "Saudi Arabian", nativeName: "العربية السعودية"},
  {code: "sn", name: "Senegal", nationality: "Senegalese", nativeName: "Sénégal"},
  {code: "rs", name: "Serbia", nationality: "Serbian", nativeName: "Србија"},
  {code: "sc", name: "Seychelles", nationality: "Seychellois", nativeName: "Seychelles"},
  {code: "sl", name: "Sierra Leone", nationality: "Sierra Leonean", nativeName: "Sierra Leone"},
  {code: "sg", name: "Singapore", nationality: "Singaporean", nativeName: "Singapore"},
  {code: "sx", name: "Sint Maarten (Dutch part)", nationality: "Dutch", nativeName: "Sint Maarten"},
  {code: "sk", name: "Slovakia", nationality: "Slovak", nativeName: "Slovensko"},
  {code: "si", name: "Slovenia", nationality: "Slovene", nativeName: "Slovenija"},
  {code: "sb", name: "Solomon Islands", nationality: "Solomon Islander", nativeName: "Solomon Islands"},
  {code: "so", name: "Somalia", nationality: "Somali", nativeName: "Soomaaliya"},
  {code: "za", name: "South Africa", nationality: "South African", nativeName: "South Africa"},
  {code: "gs", name: "South Georgia and the South Sandwich Islands", nationality: "South Georgia and the South Sandwich Islander", nativeName: "South Georgia"},
  {code: "ss", name: "South Sudan", nationality: "South Sudanese", nativeName: "South Sudan"},
  {code: "es", name: "Spain", nationality: "Spanish", nativeName: "España"},
  {code: "lk", name: "Sri Lanka", nationality: "Sri Lankan", nativeName: "śrī laṃkāva"},
  {code: "sd", name: "Sudan", nationality: "Sudanese", nativeName: "السودان"},
  {code: "sr", name: "Suriname", nationality: "Surinamer", nativeName: "Suriname"},
  {code: "sj", name: "Svalbard and Jan Mayen", nationality: "Norwegian", nativeName: "Svalbard og Jan Mayen"},
  {code: "sz", name: "Swaziland", nationality: "Swazi", nativeName: "Swaziland"},
  {code: "se", name: "Sweden", nationality: "Swedish", nativeName: "Sverige"},
  {code: "ch", name: "Switzerland", nationality: "Swiss", nativeName: "Schweiz"},
  {code: "sy", name: "Syrian Arab Republic", nationality: "Syrian", nativeName: "سوريا"},
  {code: "tw", name: "Taiwan", nationality: "Taiwanese", nativeName: "臺灣"},
  {code: "tj", name: "Tajikistan", nationality: "Tadzhik", nativeName: "Тоҷикистон"},
  {code: "tz", name: "Tanzania, United Republic of", nationality: "Tanzanian", nativeName: "Tanzania"},
  {code: "th", name: "Thailand", nationality: "Thai", nativeName: "ประเทศไทย"},
  {code: "tl", name: "Timor-Leste", nationality: "East Timorese", nativeName: "Timor-Leste"},
  {code: "tg", name: "Togo", nationality: "Togolese", nativeName: "Togo"},
  {code: "tk", name: "Tokelau", nationality: "Tokelauan", nativeName: "Tokelau"},
  {code: "to", name: "Tonga", nationality: "Tongan", nativeName: "Tonga"},
  {code: "tt", name: "Trinidad and Tobago", nationality: "Trinidadian", nativeName: "Trinidad and Tobago"},
  {code: "tn", name: "Tunisia", nationality: "Tunisian", nativeName: "تونس"},
  {code: "tr", name: "Turkey", nationality: "Turkish", nativeName: "Türkiye"},
  {code: "tm", name: "Turkmenistan", nationality: "Turkmen", nativeName: "Türkmenistan"},
  {code: "tc", name: "Turks and Caicos Islands", nationality: "Turks and Caicos Islander", nativeName: "Turks and Caicos Islands"},
  {code: "tv", name: "Tuvalu", nationality: "Tuvaluan", nativeName: "Tuvalu"},
  {code: "ug", name: "Uganda", nationality: "Ugandan", nativeName: "Uganda"},
  {code: "ua", name: "Ukraine", nationality: "Ukrainian", nativeName: "Україна"},
  {code: "ae", name: "United Arab Emirates", nationality: "Emirati", nativeName: "دولة الإمارات العربية المتحدة"},
  {code: "gb", name: "United Kingdom of Great Britain and Northern Ireland", nationality: "British", nativeName: "United Kingdom"},
  {code: "um", name: "United States Minor Outlying Islands", nationality: "American", nativeName: "United States Minor Outlying Islands"},
  {code: "us", name: "United States of America", nationality: "American", nativeName: "United States"},
  {code: "uy", name: "Uruguay", nationality: "Uruguayan", nativeName: "Uruguay"},
  {code: "uz", name: "Uzbekistan", nationality: "Uzbekistani", nativeName: "O‘zbekiston"},
  {code: "vu", name: "Vanuatu", nationality: "Ni-Vanuatu", nativeName: "Vanuatu"},
  {code: "ve", name: "Venezuela (Bolivarian Republic of)", nationality: "Venezuelan", nativeName: "Venezuela"},
  {code: "vn", name: "Viet Nam", nationality: "Vietnamese", nativeName: "Việt Nam"},
  {code: "vg", name: "Virgin Islands (British)", nationality: "Virgin Islander", nativeName: "British Virgin Islands"},
  {code: "vi", name: "Virgin Islands (U.S.)", nationality: "Virgin Islander", nativeName: "Virgin Islands of the United States"},
  {code: "wf", name: "Wallis and Futuna", nationality: "Wallis and Futuna Islander", nativeName: "Wallis et Futuna"},
  {code: "eh", name: "Western Sahara", nationality: "Sahrawi", nativeName: "الصحراء الغربية"},
  {code: "ye", name: "Yemen", nationality: "Yemeni", nativeName: "اليَمَن"},
  {code: "zm", name: "Zambia", nationality: "Zambian", nativeName: "Zambia"},
  {code: "zw", name: "Zimbabwe", nationality: "Zimbabwean", nativeName: "Zimbabwe"}
];