const langList = [
  {code: "om", nativeName: "Afaan Oromoo"},
  {code: "aa", nativeName: "Afaraf"},
  {code: "af", nativeName: "Afrikaans"},
  {code: "ak", nativeName: "Akan"},
  {code: "an", nativeName: "Aragonés"},
  {code: "ig", nativeName: "Asụsụ Igbo"},
  {code: "gn", nativeName: "Avañeẽ"},
  {code: "ae", nativeName: "Avesta"},
  {code: "ay", nativeName: "Aymar aru"},
  {code: "az", nativeName: "Azərbaycan dili"},
  {code: "id", nativeName: "Bahasa Indonesia"},
  {code: "ms", nativeName: "Bahasa Melayu, بهاس ملايو‎"},
  {code: "bm", nativeName: "Bamanankan"},
  {code: "jv", nativeName: "Basa Jawa"},
  {code: "su", nativeName: "Basa Sunda"},
  {code: "bi", nativeName: "Bislama"},
  {code: "bs", nativeName: "Bosanski jezik"},
  {code: "br", nativeName: "Brezhoneg"},
  {code: "ca", nativeName: "Català"},
  {code: "cs", nativeName: "Česky, čeština"},
  {code: "ch", nativeName: "Chamoru"},
  {code: "ny", nativeName: "ChiCheŵa, Chinyanja"},
  {code: "sn", nativeName: "ChiShona"},
  {code: "co", nativeName: "Corsu, Lingua corsa"},
  {code: "cy", nativeName: "Cymraeg"},
  {code: "da", nativeName: "Dansk"},
  {code: "se", nativeName: "Davvisámegiella"},
  {code: "de", nativeName: "Deutsch"},
  {code: "nv", nativeName: "Diné bizaad, Dinékʼehǰí"},
  {code: "et", nativeName: "Eesti, Eesti keel"},
  {code: "na", nativeName: "Ekakairũ Naoero"},
  {code: "en", nativeName: "English"},
  {code: "es", nativeName: "Español, Castellano"},
  {code: "eo", nativeName: "Esperanto"},
  {code: "eu", nativeName: "Euskara, Euskera"},
  {code: "ee", nativeName: "Eʋegbe"},
  {code: "to", nativeName: "Faka Tonga"},
  {code: "fo", nativeName: "Føroyskt"},
  {code: "fr", nativeName: "Français, Langue française"},
  {code: "fy", nativeName: "Frysk"},
  {code: "ff", nativeName: "Fulfulde, Pulaar, Pular"},
  {code: "ga", nativeName: "Gaeilge"},
  {code: "gv", nativeName: "Gaelg, Gailck"},
  {code: "sm", nativeName: "Gagana faa Samoa"},
  {code: "gd", nativeName: "Gàidhlig"},
  {code: "gl", nativeName: "Galego"},
  {code: "ki", nativeName: "Gĩkũyũ"},
  {code: "ha", nativeName: "Hausa, هَوُسَ"},
  {code: "ho", nativeName: "Hiri Motu"},
  {code: "hr", nativeName: "Hrvatski"},
  {code: "io", nativeName: "Ido"},
  {code: "rw", nativeName: "Ikinyarwanda"},
  {code: "ia", nativeName: "Interlingua"},
  {code: "ie", nativeName: "Interlingue"},
  {code: "ik", nativeName: "Iñupiaq, Iñupiatun"},
  {code: "nd", nativeName: "IsiNdebele"},
  {code: "nr", nativeName: "IsiNdebele"},
  {code: "xh", nativeName: "IsiXhosa"},
  {code: "is", nativeName: "Íslenska"},
  {code: "it", nativeName: "Italiano"},
  {code: "mh", nativeName: "Kajin M̧ajeļ"},
  {code: "kl", nativeName: "Kalaallisut, Kalaallit oqaasii"},
  {code: "kr", nativeName: "Kanuri"},
  {code: "kw", nativeName: "Kernewek"},
  {code: "kg", nativeName: "KiKongo"},
  {code: "rn", nativeName: "KiRundi"},
  {code: "sw", nativeName: "Kiswahili"},
  {code: "ht", nativeName: "Kreyòl ayisyen"},
  {code: "kj", nativeName: "Kuanyama"},
  {code: "ku", nativeName: "Kurdî, كوردی‎"},
  {code: "la", nativeName: "Latine, Lingua latina"},
  {code: "lv", nativeName: "Latviešu valoda"},
  {code: "lb", nativeName: "Lëtzebuergesch"},
  {code: "lt", nativeName: "Lietuvių kalba"},
  {code: "li", nativeName: "Limburgs"},
  {code: "ln", nativeName: "Lingála"},
  {code: "lg", nativeName: "Luganda"},
  {code: "hu", nativeName: "Magyar"},
  {code: "mg", nativeName: "Malagasy fiteny"},
  {code: "mt", nativeName: "Malti"},
  {code: "nl", nativeName: "Nederlands, Vlaams"},
  {code: "no", nativeName: "Norsk"},
  {code: "nb", nativeName: "Norsk bokmål"},
  {code: "nn", nativeName: "Norsk nynorsk"},
  {code: "oc", nativeName: "Occitan"},
  {code: "hz", nativeName: "Otjiherero"},
  {code: "ng", nativeName: "Owambo"},
  {code: "pl", nativeName: "Polski"},
  {code: "pt", nativeName: "Português"},
  {code: "ty", nativeName: "Reo Tahiti"},
  {code: "ro", nativeName: "Română"},
  {code: "rm", nativeName: "Rumantsch grischun"},
  {code: "qu", nativeName: "Runa Simi, Kichwa"},
  {code: "sc", nativeName: "Sardu"},
  {code: "za", nativeName: "Saɯ cueŋƅ, Saw cuengh"},
  {code: "st", nativeName: "Sesotho"},
  {code: "tn", nativeName: "Setswana"},
  {code: "sq", nativeName: "Shqip"},
  {code: "ss", nativeName: "SiSwati"},
  {code: "sk", nativeName: "Slovenčina"},
  {code: "sl", nativeName: "Slovenščina"},
  {code: "so", nativeName: "Soomaaliga, af Soomaali"},
  {code: "fi", nativeName: "Suomi, Suomen kieli"},
  {code: "sv", nativeName: "Svenska"},
  {code: "mi", nativeName: "Te reo Māori"},
  {code: "vi", nativeName: "Tiếng Việt"},
  {code: "ve", nativeName: "Tshivenḓa"},
  {code: "tr", nativeName: "Türkçe"},
  {code: "tk", nativeName: "Türkmen, Түркмен"},
  {code: "tw", nativeName: "Twi"},
  {code: "ug", nativeName: "Uyƣurqə, ئۇيغۇرچە‎"},
  {code: "vo", nativeName: "Volapük"},
  {code: "fj", nativeName: "Vosa Vakaviti"},
  {code: "wa", nativeName: "Walon"},
  {code: "tl", nativeName: "Wikang Tagalog"},
  {code: "wo", nativeName: "Wollof"},
  {code: "ts", nativeName: "Xitsonga"},
  {code: "sg", nativeName: "Yângâ tî sängö"},
  {code: "yo", nativeName: "Yorùbá"},
  {code: "uz", nativeName: "Zbek, Ўзбек, أۇزبېك‎"},
  {code: "el", nativeName: "Ελληνικά"},
  {code: "av", nativeName: "Авар мацӀ, магӀарул мацӀ"},
  {code: "ab", nativeName: "Аҧсуа"},
  {code: "ba", nativeName: "Башҡорт теле"},
  {code: "be", nativeName: "Беларуская"},
  {code: "bg", nativeName: "Български език"},
  {code: "os", nativeName: "Ирон æвзаг"},
  {code: "kv", nativeName: "Коми кыв"},
  {code: "ky", nativeName: "Кыргыз тили"},
  {code: "kk", nativeName: "Қазақ тілі"},
  {code: "mk", nativeName: "Македонски јазик"},
  {code: "mn", nativeName: "Монгол"},
  {code: "ce", nativeName: "Нохчийн мотт"},
  {code: "ru", nativeName: "Русский язык"},
  {code: "sr", nativeName: "Српски језик"},
  {code: "tt", nativeName: "Татарча, Tatarça, تاتارچا‎"},
  {code: "tg", nativeName: "Тоҷикӣ, Toğikī, تاجیکی‎"},
  {code: "uk", nativeName: "Українська"},
  {code: "cv", nativeName: "Чӑваш чӗлхи"},
  {code: "cu", nativeName: "Ѩзыкъ словѣньскъ"},
  {code: "ka", nativeName: "Ქართული"},
  {code: "hy", nativeName: "Հայերեն"},
  {code: "yi", nativeName: "ייִדיש"},
  {code: "he", nativeName: "עברית"},
  {code: "iw", nativeName: "עברית"},
  {code: "ur", nativeName: "اردو"},
  {code: "ar", nativeName: "العربية"},
  {code: "ps", nativeName: "پښتو"},
  {code: "fa", nativeName: "فارسی"},
  {code: "dv", nativeName: "ދިވެހި"},
  {code: "ti", nativeName: "ትግርኛ"},
  {code: "am", nativeName: "አማርኛ"},
  {code: "ks", nativeName: "कश्मीरी, كشميري‎"},
  {code: "ne", nativeName: "नेपाली"},
  {code: "pi", nativeName: "पाऴि"},
  {code: "bh", nativeName: "भोजपुरी"},
  {code: "mr", nativeName: "मराठी"},
  {code: "sa", nativeName: "संस्कृतम्"},
  {code: "sd", nativeName: "सिन्धी, سنڌي، سندھی‎"},
  {code: "hi", nativeName: "हिन्दी, हिंदी"},
  {code: "as", nativeName: "অসমীয়া"},
  {code: "bn", nativeName: "বাংলা"},
  {code: "pa", nativeName: "ਪੰਜਾਬੀ, پنجابی‎"},
  {code: "gu", nativeName: "ગુજરાતી"},
  {code: "or", nativeName: "ଓଡ଼ିଆ"},
  {code: "ta", nativeName: "தமிழ்"},
  {code: "te", nativeName: "తెలుగు"},
  {code: "kn", nativeName: "ಕನ್ನಡ"},
  {code: "ml", nativeName: "മലയാളം"},
  {code: "si", nativeName: "සිංහල"},
  {code: "th", nativeName: "ไทย"},
  {code: "lo", nativeName: "ພາສາລາວ"},
  {code: "bo", nativeName: "བོད་ཡིག"},
  {code: "my", nativeName: "ဗမာစာ"},
  {code: "km", nativeName: "ភាសាខ្មែរ"},
  {code: "iu", nativeName: "ᐃᓄᒃᑎᑐᑦ"},
  {code: "oj", nativeName: "ᐊᓂᔑᓈᐯᒧᐎᓐ"},
  {code: "cr", nativeName: "ᓀᐦᐃᔭᐍᐏᐣ"},
  {code: "ko", nativeName: "한국어 (韓國語), 조선말 (朝鮮語)"},
  {code: "ii", nativeName: "ꆈꌠ꒿ Nuosuhxop"},
  {code: "zh", nativeName: "中文 (Zhōngwén), 汉语, 漢語"},
  {code: "ja", nativeName: "日本語 (にほんご／にっぽんご)"}
];
